# Generated by Django 2.2.2 on 2019-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customoauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_applications',
            name='client_id',
            field=models.CharField(max_length=200),
        ),
    ]
