# Generated by Django 2.2.2 on 2019-06-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customoauth', '0002_auto_20190619_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
